const datos = [
  {
    id: 1,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en la playa",
    fotoAlt: "Casa en la playa",
    descripcion: "Hermosa casa frente al mar con vista panorámica.",
    habitaciones: 3,
    tipo: "Casa",
    metros: 200,
    precio: 350000
  },
  {
    id: 2,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en el campo",
    fotoAlt: "Casa en el campo",
    descripcion: "Casa campestre con amplios jardines y zona de recreación.",
    habitaciones: 4,
    tipo: "Departamento",
    metros: 300,
    precio: 280000
  },
  {
    id: 3,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en la ciudad",
    fotoAlt: "Casa en la ciudad",
    descripcion: "Cómoda casa en zona residencial cerca de todos los servicios.",
    habitaciones: 2,
    tipo: "Casa",
    metros: 150,
    precio: 210000
  },
  {
    id: 4,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en las montañas",
    fotoAlt: "Casa en las montañas",
    descripcion: "Encantadora casa con vistas espectaculares a la montaña.",
    habitaciones: 5,
    tipo: "Casa",
    metros: 250,
    precio: 420000
  },
  {
    id: 5,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en el lago",
    fotoAlt: "Casa en el lago",
    descripcion: "Acogedora casa con muelle privado en el lago.",
    habitaciones: 3,
    tipo: "Departamento",
    metros: 180,
    precio: 320000
  },
  {
    id: 6,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en el bosque",
    fotoAlt: "Casa en el bosque",
    descripcion: "Hogar tranquilo rodeado de naturaleza en un entorno forestal.",
    habitaciones: 4,
    tipo: "Departamento",
    metros: 220,
    precio: 380000
  },
  {
    id: 7,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en el centro histórico",
    fotoAlt: "Casa en el centro histórico",
    descripcion: "Elegante casa colonial en el corazón del centro histórico.",
    habitaciones: 6,
    tipo: "Casa",
    metros: 350,
    precio: 550000
  },
  {
    id: 8,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en la colina",
    fotoAlt: "Casa en la colina",
    descripcion: "Espectacular casa con vistas panorámicas desde la colina.",
    habitaciones: 4,
    tipo: "Departamento",
    metros: 280,
    precio: 480000
  },
  {
    id: 9,
    foto1: "boprincipal.jpg",
    foto2: "cocina.jpg",
    foto3: "dormitoriomatrimonio.jpg",
    titulo: "Casa en venta en el suburbio",
    fotoAlt: "Casa en el suburbio",
    descripcion: "Moderna casa con amplio jardín en un barrio tranquilo.",
    habitaciones: 3,
    tipo: "Departamento",
    metros: 190,
    precio: 290000
  }
];

export default datos;
